name: MeinBulid

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      
      - name: Setup .NET 4 🔧
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build app 🚀
        run:  msbuild WindowsFormsApplication1\WindowsFormsApplication1.sln /p:Configuration=Release /p:DeployOnBuild=true

      - name: upload 
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./bin 
